#This file is for configuring a database for Bytebase
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres   # direktori di node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv   # bind langsung ke PV di atas
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytebase-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: bytebase-db
  serviceName: bytebase-db
  replicas: 1
  template:
    metadata:
      labels:
        app: bytebase-db
    spec:
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRESQL_USERNAME
              value: bytebase
            - name: POSTGRESQL_PASSWORD
              value: bytebase
            - name: POSTGRESQL_DATABASE
              value: bytebase
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeCLaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bytebase-db
  namespace: default
  labels:
    app: bytebase-db
spec:
  ports:
    - port: 5432
      name: postgresql
  clusterIP: None
  selector:
    app: bytebase-db
